---
kind: pipeline
type: docker
name: linux-amd64
platform:
  os: linux
  arch: amd64
steps:
  - name: ci
    image: rancher/dapper:v0.6.0
    environment:
      DRONE_TAG: ${DRONE_TAG}
      DRONE_COMMIT_SHA: ${DRONE_COMMIT_SHA}
    commands:
      - dapper ci
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - push
        - pull_request
        - tag
  - name: github_release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      prerelease: false
      files:
      title: "${DRONE_TAG}"
    when:
      ref:
        include:
          - "refs/tags/v*"
        exclude:
          - "refs/tags/*-rc*"
          - "refs/tags/*-alpha*"
          - "refs/tags/*-beta*"
  - name: github_prerelease
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      title: "Pre-release ${DRONE_TAG}"
    when:
      ref:
        include:
          - "refs/tags/*-rc*"
          - "refs/tags/*-alpha*"
          - "refs/tags/*-beta*"
  - name: docker-publish
    image: plugins/docker
    settings:
      dockerfile: package/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: "cnrancher/hangar"
      tag: "${DRONE_TAG}-amd64"
    when:
      event:
        - tag
  - name: docker-build
    image: plugins/docker
    settings:
      dockerfile: package/Dockerfile
      repo: "cnrancher/hangar"
      tag: "${DRONE_COMMIT}-amd64"
      dry_run: true
    when:
      event:
        - push
        - pull_request
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
node:
  instance: agent-amd64

---
kind: pipeline
type: docker
name: linux-arm64
platform:
  os: linux
  arch: arm64
steps:
  - name: ci
    image: rancher/dapper:v0.6.0
    environment:
      DRONE_TAG: ${DRONE_TAG}
      DRONE_COMMIT_SHA: ${DRONE_COMMIT_SHA}
    commands:
      - dapper ci
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - push
        - pull_request
        - tag
  - name: docker-publish
    image: plugins/docker
    settings:
      dockerfile: package/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: "cnrancher/hangar"
      tag: "${DRONE_TAG}-arm64"
    when:
      event:
        - tag
  - name: docker-build
    image: plugins/docker
    settings:
      dockerfile: package/Dockerfile
      repo: "cnrancher/hangar"
      tag: "${DRONE_COMMIT}-arm64"
      dry_run: true
    when:
      event:
        - push
        - pull_request
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
node:
  instance: agent-arm64

---
kind: pipeline
type: docker
name: manifest
platform:
  os: linux
  arch: amd64
steps:
  - name: manifest
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      platforms:
        - linux/amd64
        - linux/arm64
      target: "cnrancher/hangar:${DRONE_TAG}"
      template: "cnrancher/hangar:${DRONE_TAG}-ARCH"
    when:
      event:
        - tag
  - name: manifest-latest
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      platforms:
        - linux/amd64
        - linux/arm64
      target: "cnrancher/hangar:latest"
      template: "cnrancher/hangar:${DRONE_TAG}-ARCH"
    when:
      event:
        - tag
      ref:
        include:
          - refs/tags/v*
        exclude:
          - refs/tags/*-rc*
          - refs/tags/*-alpha*
          - refs/tags/*-beta*
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
trigger:
  event:
    include:
      - tag
depends_on:
  - linux-amd64
  - linux-arm64
node:
  instance: agent-amd64
