FROM registry.suse.com/bci/python:3.11

ENV DAPPER_SOURCE /go/src/github.com/cnrancher/hangar/
ENV DAPPER_DOCKER_SOCKET=true
WORKDIR ${DAPPER_SOURCE}

RUN zypper ref && \
    zypper in -y -f libdevmapper1_03 vim wget docker awk unzip jq && \
    zypper clean && \
    curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash && \
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash && \
    curl -LO https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl && \
    chmod +x kubectl && mv kubectl /usr/local/bin

RUN pip install pytest tox

COPY bin/hangar /usr/local/bin/hangar
COPY package/default-policy.json /etc/containers/policy.json
COPY package/registries.d/default.yaml /etc/containers/registries.d/default.yaml

ENV DAPPER_RUN_ARGS "--network=host"

ENTRYPOINT [ "test/scripts/run.sh" ]
CMD [ "--all" ]
