FROM registry.suse.com/bci/python:3.10

ENV DAPPER_ENV SOURCE_REGISTRY SOURCE_USERNAME SOURCE_PASSWORD \
DEST_REGISTRY DEST_USERNAME DEST_PASSWORD TEST_SKIP_TLS
ENV DAPPER_SOURCE /source/test
ENV DAPPER_DOCKER_SOCKET=true
WORKDIR ${DAPPER_SOURCE}

# skopeo
COPY --from=docker.io/cnrancher/hardened-skopeo:v1.14.1 /usr/bin/skopeo /usr/bin/

RUN zypper up -y && \
    zypper in -y -f libdevmapper1_03 vim wget git && \
    zypper clean
RUN skopeo -v
RUN pip install pytest

ENTRYPOINT [ "test/scripts/entrypoint.sh" ]
