name: "Install Hangar"
description: "Install hangar in workflow"
inputs:
  version:
    description: "Hangar version"
    default: "v1.9.0-beta.5"
    required: true

runs:
  using: "composite"
  steps:
  - name: Install Hangar
    shell: bash
    run: |
      set -ex
      curl -fsL https://github.com/cnrancher/hangar/releases/download/${{ inputs.version }}/hangar_Linux_$(uname -m).tar.gz | tar zx
      sudo mv hangar_Linux_$(uname -m)/hangar /usr/local/bin/hangar
      sudo rm -rf hangar_*

      hangar version
