name: "Hangar Sign Actions"
description: "hangar sign images in workflow"
inputs:
  version:
    description: "Hangar version"
    default: "v1.9.0"
    required: true
  images:
    description: "Image list"
    default: ""
    required: true
  cosign_key:
    description: "sign image with cosign private key (Optional: Sign image in keyless mode if not provided)"
  cosign_key_password:
    description: "cosign private key password"
  debug:
    description: "enable debug output"
    default: "false"
  jobs:
    description: "sign worker num"
    default: "3"
  arch:
    description: "sign image arch"
    default: "amd64,arm64"
  os:
    description: "sign image os"
    default: "linux"

runs:
  using: "composite"
  steps:
  - name: Install Hangar
    shell: bash
    run: |
      set -ex
      curl -fsL https://github.com/cnrancher/hangar/releases/download/${{ inputs.version }}/hangar_Linux_$(uname -m).tar.gz | tar zx
      sudo mv hangar_Linux_$(uname -m)/hangar /usr/local/bin/hangar
      sudo rm -rf hangar_*

      mkdir -p /home/runner/.config/containers/

      cat > /home/runner/.config/containers/policy.json << EOF
      {
          "default": [
              {
                  "type": "insecureAcceptAnything"
              }
          ],
          "transports":
              {
                  "docker-daemon":
                      {
                          "": [{"type":"insecureAcceptAnything"}]
                      }
              }
      }
      EOF

      hangar version
  - name: Hangar sign images
    shell: bash
    run: |
      set -e
      TMP_DIR=$(mktemp -d)
      WORK_DIR=$(pwd)
      cd $TMP_DIR
      cat > images.txt << EOT
      ${{ inputs.images }}
      EOT
      echo Images:
      cat images.txt

      if [[ "${{ inputs.cosign_key }}" != "" ]]; then
        echo "::add-mask::${{ inputs.cosign_key }}"
        echo "::add-mask::${{ inputs.cosign_key_password }}"
        echo -n "${{ inputs.cosign_key_password }}" > password.txt
        cat > sigstore.key << EOT
      ${{ inputs.cosign_key }}
      EOT

        set -x

        hangar sign -f images.txt \
          -j=${{ inputs.jobs }} \
          --arch=${{ inputs.arch }} \
          --os=${{ inputs.os }} \
          --debug=${{ inputs.debug }} \
          --key=sigstore.key \
          --passphrase-file=password.txt \
          --auto-yes

        set +x

      else

        set -x

        hangar sign -f images.txt \
          -j=${{ inputs.jobs }} \
          --arch=${{ inputs.arch }} \
          --os=${{ inputs.os }} \
          --debug=${{ inputs.debug }} \
          --oidc-provider=github-actions \
          --auto-yes

        set +x

      fi

      cd $WORK_DIR
      rm -rf $TMP_DIR

      echo Done
