name: CI
on:
  pull_request:
  push:
    branches:
      - main
      - dev
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgpgme-dev libassuan-dev libbtrfs-dev libdevmapper-dev pkg-config gcc
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61
      - name: Verify
        run: |
          make verify
      - name: Test
        run: |
          make test
      - name: Build
        env:
          TAG: ${{ github.ref_name }}
          COMMIT: ${{ github.sha }}
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: build --clean --snapshot
      - name: Image Build
        run: |
          make image
        env:
          TAG: dev
          REPO: cnrancher
