name: CI
on:
  pull_request:
  push:
    tags-ignore: [ '**' ]
    branches:
      - main
      - dev*
jobs:
  ci:
    runs-on: ${{ github.repository_owner == 'cnrancher' && 'org-cnrancher-runner-dind-x64' || 'ubuntu-latest' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install hangar test
        uses: ./.github/actions/install-hangar
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24.x
          cache: false
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgpgme-dev libassuan-dev libbtrfs-dev libdevmapper-dev pkg-config gcc
      - name: Lint
        uses: golangci/golangci-lint-action@v8
      - name: Verify
        run: |
          ./scripts/verify.sh
      - name: Test
        run: |
          ./scripts/test.sh
      - name: Build
        env:
          TAG: ${{ github.ref_name }}
          COMMIT: ${{ github.sha }}
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: build --clean --snapshot
      - name: Image Build
        run: |
          ./scripts/image.sh
        env:
          TAG: dev
          REGISTRY: ${{ vars.TCR_REGISTRY }}
          REPO: ${{ vars.PUBLIC_REGISTRY_REPO }}
