name: CI
on:
  push:
    tags:
      - 'v*'
jobs:
  ci:
    permissions:
      contents: write # required for creating GH release
      id-token: write # required for reading vault secrets
    runs-on: ubuntu-latest
    steps:
      # - name: Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ vars.PUBLIC_REGISTRY }}
      #     username: ${{ secrets.PUBLIC_REGISTRY_USERNAME }}
      #     password: ${{ secrets.PUBLIC_REGISTRY_PASSWORD }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Dependencies
        run: |
          sudo apt update
          sudo apt --yes install libgpgme-dev libassuan-dev libbtrfs-dev libdevmapper-dev pkg-config gcc
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
      - name: Verify
        run: |
          ./scripts/verify.sh
      - name: Test
        run: |
          ./scripts/test.sh
      - name: Static Build
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
      # - name: Image Push
      #   run: |
      #     make image-push
      #   env:
      #     TAG: ${{ github.ref_name }}
      #     REPO: ${{ vars.PUBLIC_REGISTRY }}/${{ vars.PUBLIC_REGISTRY_REPO }}
